Protect other secbox instances when --destroy
Solves #3

diff --git a/secbox b/secbox
--- a/secbox
+++ b/secbox
@@ -251,6 +251,12 @@ secbox_instances_using_sshfs() {
     echo "$_instances"
 }
 
+other_secbox_instances() {
+    local _instances=0
+    _instances=$(pgrep --count --full "podman .*secbox")
+    echo "$_instances"
+}
+
 sudo_privs() {
     sudo -nv >/dev/null 2>&1
 }
@@ -599,12 +605,16 @@ secbox_exec() {
 secbox_destroy(){
     secbox_container_exists || die "${orange}[*]${no_format} ${container} does not exist"
 
+    if [[ $(other_secbox_instances) -gt 0 ]]; then
+        die "${orange}[*]${no_format} Destruction aborted: other secbox instances are using the container"
+    fi
+
     print_logo
 
     # -f bypasses the interactive prompt
     if [[ "${1:-}" != "-f" ]]; then
         read -ep "[.] Do you really want to destroy secbox [y/N] " -n 1 -r
-        [[ $REPLY =~ ^[Yy]$ ]] || die "${orange}[*]${no_format} Abort destruction."
+        [[ $REPLY =~ ^[Yy]$ ]] || die "${orange}[*]${no_format} Destruction aborted."
     else
         shift
     fi
